import Head from "next/head";
// import Image from "next/image";
// import cardStyles from "../Assets/Styles/Card/Card.module.css";
import Header  from "../layout/Header/Header";
import MainHero  from "../layout/MainHero";
import Slider from "../components/slider/MainSlider";
import Main from "../components/card/Main";
import Group from "../components/card/Group";
import Programs from "../components/card/Programs";
import Gallery from "../components/card/Gallery";
import Scholarships from "../components/card/Scholarships";
import Footer from "../layout/Footer/Footer";

const history = () => {
  return (
    <>
      <Head>
        <title>SIBA KDK</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <MainHero
      data={{
        content:"The Sukkur Institute of Business Administration is a public sector degree awarding Institute approved by Higher Education Commission and chartered by the Government of Sindh. In 1994, the Sukkur Institute of Business Administration was established for business education, initially in the hired building of Public School, Sukkur. The Senate is the governing body of the Institute. Governor of Sindh is the chancellor. Initially, Sukkur IBA was affiliated to IBA Karachi."
      }}
      />
      <Footer />
    </>
  );
};

export default history;
